version: '3.7'
services:
  nginx:
    build:
      context: ./nginx
    ports:
      - '3052:80'
    depends_on:
      - api
      - client
    restart: always
  client:
    build:
      context: ./client
    depends_on:
      - api
    restart: always
  api:
    build:
      context: ./server
    volumes:
      - ./server:/app
    environment: 
      - FLASK_ENV=production
    restart: always