version: '3.7'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3051:80'
    depends_on:
      - api
      - client
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /home/node/app/node_modules
      - ./client:/home/node/app
    depends_on:
      - api
    environment: 
      - REACT_APP_API=stock-analyzer
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - ./server:/app
    environment: 
      - FLASK_ENV=development