export const FETCH_DATA = "FETCH_DATA";
export const RESET_FETCH_DATA = "RESET_FETCH_DATA";
export const CHANGE_MODE = "CHANGE_MODE";

export const ANALYZE_OPTIONS = "ANALYZE_OPTIONS";
export const SET_MODAL = "SET_MODAL";
export const PREPARE_DOWNLOAD = "PREPARE_DOWNLOAD";

export const NOTIFY = "NOTIFY";
export const GET_OPTION_CHAIN = "GET_OPTION_CHAIN";
export const DOWNLOAD_DATA = "DOWNLOAD_DATA";
export const SET_FORM_VALUES = "SET_FORM_VALUES";

export const UPTREND = "UPTREND";
export const CHANGE_OPTION = "CHANGE_OPTION";
export const CHANGE_DATE = "CHANGE_DATE";
export const RESET = "RESET";

export const EQUITY_TREND = "EQUITY_TREND";
export const GET_OPTION_VALUES = "GET_OPTION_VALUES";
export const SET_PROGRESS = "SET_PROGRESS";
export const RESET_OPTIONTREND = "RESET_OPTIONTREND";
export const RESET_EQUITYTREND = "RESET_EQUITYTREND";

export const SELECTED_TICKER = "SELECTED_TICKER";
export const UNSELECT_TICKER = "UNSELECT_TICKER"
export const FETCH_DATA_UPTREND = "FETCH_DATA_UPTREND";
export const RESET_TICKERDATA = "RESET_TICKERDATA";
export const RESET_TICKER = "RESET_TICKER";

export const GET_OPTION_RANK = "GET_OPTION_RANK";
export const CHANGE_TAB = "CHANGE_TAB"
export const RESET_PROGRESS= "RESET_PROGRESS"

export const GET_EXPIRY = "GET_EXPIRY"
export const SELECTED_EXPIRY= "SELECTED_EXPIRY"

export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";